module.exports = [
    // {name:'anckle', src:'./img/partsOfBody/anckle.png', audio:'./audio/arm.mp3'},
    {name:'apple', src:'./img/fruits&vegetables/apple.png', audio:'./audio/apple.mp3'},
    {name:'banana', src:'./img/fruits&vegetables/banana.png', audio:'./audio/banana.mp3'},
    {name:'cabbage', src:'./img/fruits&vegetables/cabbage.png', audio:'./audio/cabbage.mp3'},
    {name:'carrot', src:'./img/fruits&vegetables/carrot.png', audio:'./audio/carrot.mp3'},
    {name:'cherry', src:'./img/fruits&vegetables/cherries.png', audio:'./audio/cherry.mp3'},
    {name:'coconut', src:'./img/fruits&vegetables/coconut.png', audio:'./audio/coconut.mp3'},
    {name:'corn', src:'./img/fruits&vegetables/corn.png', audio:'./audio/corn.mp3'},
    {name:'cranberry', src:'./img/fruits&vegetables/cranberies.png',audio:'./audio/cranberry.mp3'},
    {name:'grapes', src:'./img/fruits&vegetables/grapes.png',audio:'./audio/grape.mp3'},
    {name:'kiwi', src:'./img/fruits&vegetables/kiwi.png',audio:'./audio/kiwi.mp3'},
    {name:'lemon', src:'./img/fruits&vegetables/lemon.png',audio:'./audio/lemon.mp3'},
    {name:'onion', src:'./img/fruits&vegetables/onion.png',audio:'./audio/onion.mp3'},
    {name:'orange', src:'./img/fruits&vegetables/orange.png',audio:'./audio/orange.mp3'},
    {name:'peach', src:'./img/fruits&vegetables/peach.png',audio:'./audio/peach.mp3'},
    {name:'pear', src:'./img/fruits&vegetables/pear.png',audio:'./audio/pear.mp3'},
    {name:'pepper', src:'./img/fruits&vegetables/pepper.png',audio:'./audio/pepper.mp3'},
    {name:'plum', src:'./img/fruits&vegetables/plum.png',audio:'./audio/plum.mp3'},
    {name:'potato', src:'./img/fruits&vegetables/potato.png',audio:'./audio/potato.mp3'},
    {name:'pumpkin', src:'./img/fruits&vegetables/pumpkin.png',audio:'./audio/pumpkin.mp3'},
    {name:'raspberry', src:'./img/fruits&vegetables/raspberries.png',audio:'./audio/raspberry.mp3'},
    {name:'strawberry', src:'./img/fruits&vegetables/strawberry.png',audio:'./audio/strawberry.mp3'},
    {name:'tomato', src:'./img/fruits&vegetables/tomato.png',audio:'./audio/tomato.mp3'},
    {name:'watermelon', src:'./img/fruits&vegetables/watermelon.png',audio:'./audio/watermelon.mp3'}

]